export const RIOTGAMES_LOL = "https://br1.api.riotgames.com/lol/"
export const RIOTGAMES_ACCOUNT = "https://americas.api.riotgames.com/riot/account/v1/accounts/"
export const RIOTGAMES_AMERICAS_LOL = "https://americas.api.riotgames.com/lol/"
export const LOL_CDN = "https://ddragon.leagueoflegends.com/cdn/13.18.1/"
export const CDN_COMMUNITY_DRAGON ="https://cdn.communitydragon.org/13.18.1/"
